plugins:
  guest_guard_enabled:
    default: true
    client: true
    type: bool

  guest_guard_paths:
    # Paths to protect (guests hitting these are redirected to login).
    # Enter one per line in Admin UI. Supports exact match or prefix with '*'.
    # Examples:
    #   /discourse-ai/ai-bot/conversations
    #   /my/*
    default: ""
    client: true
    type: list

  guest_guard_login_url:
    # Where to send guests (relative or absolute).
    # If you use DiscourseConnect/SSO, consider /login-required.
    default: "/login"
    client: true
    type: text

  guest_guard_preserve_destination:
    # Append the original URL as a query param to the login URL.
    default: true
    client: true
    type: bool

  guest_guard_return_param:
    # The name of the query param used when preserving destination.
    # Common: redirect_to or return_to
    default: "redirect_to"
    client: true
    type: text

  guest_guard_allow_param:
    # Allow support bypass with ?noredirect=1
    default: true
    client: true
    type: bool

  guest_guard_min_trust_level:
    # Guests are always redirected.
    # If >= 0, logged-in users with TL < value are also redirected.
    # -1 disables TL check (only guests redirected).
    default: -1
    client: true
    type: enum
    choices:
      - -1
      - 0
      - 1
      - 2
      - 3
      - 4
